[package]
name = "image_generation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
rand = "0.8.4"
rand_pcg = "0.3.1"
rand_seeder = "0.2.2"
